name: HideyQOL
version: '${project.version}'
main: com.samifying.hideyqol.Main
api-version: 1.20
softdepend:
  - EssentialsX
authors: [ Rooot ]
description: Quality-of-Life features for the HideySMP Minecraft server
commands:
  portalcalc:
    description: Calculate the coordinates of a portal
    usage: /portalcalc
    aliases: [ pc ]
  setmaxplayers:
    description: Change the max player count of the server
    permission: hideyqol.setmaxplayers
    usage: /setmaxplayers <maxplayers>
